PinochoWeb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from Apps.Alumnos.views import Home, ListadoAlumnos, ListadoPadres, NuevoAlumno, NuevoPadre, AlumnoEdit, AlumnoDelete, PadreEdit, PadreDelete
from Apps.Adeudos.views import NuevoAdeudo, ListadoAdeudos, AdeudoEdit, AdeudoDelete
from Apps.Contabilidad.views import ListadoIngresos, NuevoIngreso, IngresoDelete, IngresoEdit, ListadoGastos, \
                                    NuevoGasto, GastoDelete, GastoEdit, CategoriasIngresos, CategoriasGastos, \
                                    NuevaCatIngreso, NuevaCatGastos, Portada_contabilidad, Portada_contabilidad_plus, \
                                    Portada_contabilidad_plus2, CatGastoDelete, CatGastoEdit, CatIngresoEdit, CatIngresoDelete, \
                                    ReciboPDF, NuevoRecibo, EditarRecibo, ListadoRecibos, ReciboDelete   
                                       
from Apps.Login.views import Login, LogoutUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(Home.as_view()), name = 'Home'),
    path('accounts/login/', Login.as_view(), name = 'Login'),
    path('logout/', LogoutUser, name = 'Logout'),
    path('Alumnos/', login_required(ListadoAlumnos.as_view()), name = 'Alumnos'),
    path('Padres/', login_required(ListadoPadres.as_view()), name = 'Padres'),
    path('NuevoAlumno/', login_required(NuevoAlumno.as_view()), name = 'NuevoAlumno'),
    path('NuevoPadre/', login_required(NuevoPadre.as_view()), name = 'NuevoPadre'),
    path('AlumnoEdit/<int:pk>/', login_required(AlumnoEdit.as_view()), name = 'AlumnoEdit'),
    path('AlumnoDelete/<int:pk>/', login_required(AlumnoDelete.as_view()), name = 'AlumnoDelete'),
    path('PadreEdit/<int:pk>/', login_required(PadreEdit.as_view()), name = 'PadreEdit'),
    path('PadreDelete/<int:pk>/', login_required(PadreDelete.as_view()), name = 'PadreDelete'),
    #ADEUDOS
    path('Adeudos/', login_required(ListadoAdeudos.as_view()), name = 'Adeudos'),
    path('NuevoAdeudo/', login_required(NuevoAdeudo.as_view()), name = 'NuevoAdeudo'),
    path('AdeudoEdit/<int:pk>/', login_required(AdeudoEdit.as_view()), name = 'AdeudoEdit'),
    path('AdeudoDelete/<int:pk>/', login_required(AdeudoDelete.as_view()), name = 'AdeudoDelete'),
    #CONTABILIDAD
    path('Portada_contabilidad/', login_required(Portada_contabilidad.as_view()), name = 'Portada_contabilidad'),
    path('Portada_contabilidad_plus/', login_required(Portada_contabilidad_plus.as_view()), name = 'Portada_contabilidad_plus'),
    path('Portada_contabilidad_plus2/', login_required(Portada_contabilidad_plus2.as_view()), name = 'Portada_contabilidad_plus2'),
    path('Ingresos/', login_required(ListadoIngresos.as_view()), name = 'Ingresos'),
    path('NuevoIngreso/', login_required(NuevoIngreso.as_view()), name = 'NuevoIngreso'),
    path('IngresoEdit/<int:pk>/', login_required(IngresoEdit.as_view()), name = 'IngresoEdit'),
    path('IngresoDelete/<int:pk>/', login_required(IngresoDelete.as_view()), name = 'IngresoDelete'),
    path('Gastos/', login_required(ListadoGastos.as_view()), name = 'Gastos'),
    path('NuevoGasto/', login_required(NuevoGasto.as_view()), name = 'NuevoGasto'),
    path('GastoEdit/<int:pk>/', login_required(GastoEdit.as_view()), name = 'GastoEdit'),
    path('GastoDelete/<int:pk>/', login_required(GastoDelete.as_view()), name = 'GastoDelete'),
    path('Categorias_Ingresos/', login_required(CategoriasIngresos.as_view()), name = 'CategoriasIngresos'),
    path('Nueva_Cat_Gasto/', login_required(NuevaCatGastos.as_view()), name = 'NuevaCatGastos'),
    path('Categorias_Gastos/', login_required(CategoriasGastos.as_view()), name = 'CategoriasGastos'),
    path('Nueva_Cat_Ingresos/', login_required(NuevaCatIngreso.as_view()), name = 'NuevaCatIngresos'),
    path('Cat_Gastos_Delete/<int:pk>/', login_required(CatGastoDelete.as_view()), name = 'CatGastoDelete'),
    path('Cat_Gastos_Edit/<int:pk>/', login_required(CatGastoEdit.as_view()), name = 'CatGastoEdit'),
    path('Cat_Ingresos_Delete/<int:pk>/', login_required(CatIngresoDelete.as_view()), name = 'CatIngresoDelete'),
    path('Cat_Ingresos_Edit/<int:pk>/', login_required(CatIngresoEdit.as_view()), name = 'CatIngresoEdit'),
    #RECIBOS
    path('NuevoRecibo/', login_required(NuevoRecibo.as_view()), name = 'NuevoRecibo'),
    path('ListadoRecibos/', login_required(ListadoRecibos.as_view()), name = 'Recibos'),
    path('EditRecibo/<int:pk>/', login_required(EditarRecibo.as_view()), name = 'ReciboEdit'),
    path('BorrarRecibo/<int:pk>/', login_required(ReciboDelete.as_view()), name = 'ReciboDelete'),
    path('ReciboPDF/<int:pk>/', login_required(ReciboPDF.as_view()), name = 'ReciboPDF'),
] + static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

Apps/Contabilidad/models.py
from django.db import models
from datetime import datetime
from PinochoWeb import settings
from Apps.Alumnos.models import Padre

# Create your models here.

class year(models.Model):
    
    actual_year = datetime.now().year
    ano = models.CharField(max_length=4, default=actual_year)

    def __str__(self):

        return  '%s' % self.ano 

class Cat_Ingreso(models.Model):

    Id = models.AutoField(primary_key=True)
    categoria = models.CharField(max_length=30)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:

        verbose_name='Categoria Ingreso'
        verbose_name_plural='Categorias Ingreso'   

    def __str__(self):

        return  '%s' % self.categoria 

class Cat_Gasto(models.Model):

    Id = models.AutoField(primary_key=True)
    categoria = models.CharField(max_length=30)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:

        verbose_name='Categoria Gasto'
        verbose_name_plural='Categorias Gastos'   

    def __str__(self):

        return  '%s' % self.categoria         

class Ingreso(models.Model):

    Id = models.AutoField(primary_key=True)
    concepto = models.CharField(max_length=30)
    categoria = models.ForeignKey(Cat_Ingreso, null=True, blank=True, on_delete=models.CASCADE)
    fecha = models.DateField()
    cantidad = models.FloatField(default=0.00)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)  

    class Meta:

        verbose_name='Ingreso'
        verbose_name_plural='Ingresos'   

    def __str__(self):

        return  '%s %s' % (self.concepto, self.cantidad)


class Gasto(models.Model):

    Id = models.AutoField(primary_key=True)
    concepto = models.CharField(max_length=30)
    categoria = models.ForeignKey(Cat_Gasto, null=True, blank=True, on_delete=models.CASCADE)
    fecha = models.DateField()
    cantidad = models.FloatField(default=0.00)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)  

    class Meta:

        verbose_name='Gasto'
        verbose_name_plural='Gastos'   

    def __str__(self):

        return  '%s %s' % (self.concepto, self.cantidad)  

class Recibo(models.Model):

    Id = models.AutoField(primary_key=True)
#    nombre = models.CharField(max_length=30, blank=True, null=True)
#    apellidos = models.CharField(max_length=50, blank=True, null=True)
#    dni = models.CharField(max_length=9, blank=True, null=True)
    padre = models.ForeignKey(Padre, null=True, blank=True, on_delete=models.CASCADE)
    concepto = models.CharField(max_length=30)
    fecha = models.DateField()
    cantidad = models.FloatField(default=0.00)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)  

    class Meta:

        verbose_name='Recibo'
        verbose_name_plural='Recibos'   

    def __str__(self):

        return  '%s %s' % (self.concepto, self.cantidad)  

Apps/Alumnos/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect,HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, TemplateView, DeleteView
from django.urls import reverse_lazy
from .models import Curso, Clase, Alumno, Padre
from Apps.Contabilidad.models import Ingreso, Gasto
from .forms import AlumnoForm, PadreForm
from datetime import datetime


# Create your views here.

class Home(TemplateView):

    template_name = 'home.html'

    @classmethod
    def ano(request):
        data = datetime.today().year
        curso = str('20/21')
        return curso

    @classmethod
    def get_total_ingresos(cls):
        data = sum([Ingreso.cantidad for Ingreso in Ingreso.objects.all()])
        return data

    @classmethod
    def get_ingresos_mes(cls):
        total = dict()
        total_plus = dict()
        ano = datetime.today().year
        anoplus = ano + 1
        for i in range(1, 13):
            total_mes = sum([Ingreso.cantidad for Ingreso in Ingreso.objects.filter(fecha__month= i, fecha__year= ano)])
            total [i] = total_mes
            valores = list(total.values())
            valores_final = valores[8:13]
        for i in range(1, 13):
            total_mes_plus = sum([Ingreso.cantidad for Ingreso in Ingreso.objects.filter(fecha__month= i, fecha__year= anoplus)])
            total_plus [i] = total_mes_plus
            valores_plus = list(total_plus.values())
            valores_final_plus = valores_plus[0:8]

        valores_final.extend(valores_final_plus)
        return valores_final

    @classmethod
    def get_total_ingresos_curso(cls):
        ingresos = cls.get_ingresos_mes()
        total = sum(ingresos)
        return total     

    @classmethod
    def get_total_gastos(cls):
        data = sum([Gasto.cantidad for Gasto in Gasto.objects.all()])
        return data

    @classmethod
    def get_gastos_mes(cls):
        total = dict()
        total_plus = dict()
        ano = datetime.today().year
        anoplus = ano + 1
        for i in range(1, 13):
            total_mes = sum([Gasto.cantidad for Gasto in Gasto.objects.filter(fecha__month= i, fecha__year= ano)])
            total [i] = total_mes
            valores = list(total.values())
            valores_final = valores[8:13]
        for i in range(1, 13):
            total_mes_plus = sum([Gasto.cantidad for Gasto in Gasto.objects.filter(fecha__month= i, fecha__year= anoplus)])
            total_plus [i] = total_mes_plus
            valores_plus = list(total_plus.values())
            valores_final_plus = valores_plus[0:8]

        valores_final.extend(valores_final_plus)
        return valores_final    

    @classmethod
    def get_total_gastos_curso(cls):
        gastos = cls.get_gastos_mes()
        total = sum(gastos)
        return total   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        context['grafico_ingresos'] = self.get_ingresos_mes()
        context['grafico_gastos'] = self.get_gastos_mes()
        context['total_ingresos_curso'] = self.get_total_ingresos_curso()
        context['total_gastos_curso'] = self.get_total_gastos_curso()
        context['ano'] = self.ano()
        return context

class ListadoAlumnos(ListView):

    model = Alumno
    template_name = 'Alumnos.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Alumnos'
        context['submit']= reverse_lazy('NuevoAlumno')
        return context

class ListadoPadres(ListView):

    model = Padre
    template_name = 'Padres.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Padres'
        context['submit']= reverse_lazy('NuevoPadre')
        return context        
    
class NuevoAlumno(CreateView):

    model = Alumno
    form_class = AlumnoForm
    template_name = 'NuevoAlumno.html'   
    success_url = reverse_lazy('Alumnos') 

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Nuevo Alumno'
        context['cancel']= reverse_lazy('Alumnos')
        context['submit'] = 'Añadir'
        return context

class NuevoPadre(CreateView):

    model = Padre
    form_class = PadreForm
    template_name = 'NuevoPadre.html'   
    success_url = reverse_lazy('Padres') 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Nuevo Padre/Madre'
        context['cancel']= reverse_lazy('Padres')
        context['submit'] = 'Añadir'
        
        return context

class AlumnoEdit(UpdateView):

    model = Alumno
    form_class = AlumnoForm
    template_name = 'NuevoAlumno.html'   
    success_url = reverse_lazy('Alumnos') 

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de Alumno'
        context['cancel']= reverse_lazy('Alumnos')
        context['submit'] = 'Actualizar'
        return context    

class AlumnoDelete(DeleteView):

    model = Alumno
    template_name = 'AlumnoDelete.html'  
    success_url = reverse_lazy('Alumnos')  

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de Alumno'
        context['cancel']= reverse_lazy('Alumnos')
        return context    

class PadreEdit(UpdateView):

    model = Padre
    form_class = PadreForm
    template_name = 'NuevoPadre.html'   
    success_url = reverse_lazy('Padres') 

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de Padre'
        context['cancel']= reverse_lazy('Padres')
        context['submit'] = 'Actualizar'
        return context    

class PadreDelete(DeleteView):

    model = Padre
    template_name = 'PadreDelete.html'  
    success_url = reverse_lazy('Padres')  

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de Padre'
        context['cancel']= reverse_lazy('Padres')
        return context          
    

Apps/Alumnos/templates/AlumnoDelete.html
{% extends "base.html" %}

{% load static %}

{% block content %}



    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Estas seguro de eliminar el registro Nº {{ object.Id }}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{% url 'Alumnos' %}" class="btn btn-info btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>


{% endblock %}

Apps/Alumnos/templates/AlumnoEdit.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  {% include "template_form.html" %}

{% endblock %}

Apps/Alumnos/templates/Alumnos.html
{% extends 'list.html' %}

{% block columns %}
    <tr>
        <!-- <th scope="col">Foto</th> -->
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Clase</th>
        <th scope="col">Padre/Madre</th>
        <th scope="col">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for c in object_list %}
        <tr>
           <!--  <td>   
            {% if c.imagen %}    
                <img src="{{c.imagen.url}}" height="80rem" width="70rem" style="border-radius: 5px;"/>
            {% endif %}    
            </td> -->
            <td>{{ c.Id }}</td>
            <td>{{ c.Nombre }}</td>
            <td>{{ c.Apellidos }}</td>
            <td>{{ c.Clase }}</td>
            <td>{{ c.Padre }}</td>
            <td class="">
                <a title="Editar Registro" href="{% url 'AlumnoEdit' c.Id %}" class="btn btn-info btn-sm btn-flat">
                    <i class="fas fa-edit"></i>
                </a>
                <a title="Eliminar Registro" href="{% url 'AlumnoDelete' c.Id %}" class="btn btn-danger btn-sm btn-flat">
                    <i class="fas fa-trash-alt"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

Apps/Alumnos/templates/NuevoAlumno.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  {% include "template_form.html" %}

{% endblock %}

Apps/Alumnos/templates/NuevoPadre.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  {% include "template_form.html" %}

{% endblock %}

Apps/Alumnos/templates/PadreEdit.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  {% include "template_form.html" %}

{% endblock %}

Apps/Alumnos/templates/Padres.html
{% extends 'list.html' %}

{% block columns %}
    <tr>
        <th scope="col">D.N.I.</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Numero de cuenta</th>
        <th scope="col">Teléfono 1</th>
        <th scope="col">Teléfono 2</th>
        <th scope="col">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for c in object_list %}
        <tr>
            <td>{{ c.dni }}</td>
            <td>{{ c.Nombre }}</td>
            <td>{{ c.Apellidos }}</td>
            <td>{{ c.NumeroCuenta }}</td>
            <td>{{ c.Telefono1 }}</td>
            <td>{{ c.Telefono2 }}</td>
            <td>
                <a title="Editar Registro" href="{% url 'PadreEdit' c.Id %}" class="btn btn-info btn-sm btn-flat">
                    <i class="fas fa-edit"></i>
                </a>
                <a title="Eliminar Registro" href="{% url 'PadreDelete' c.Id %}" class="btn btn-danger btn-sm btn-flat">
                    <i class="fas fa-trash-alt"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

Apps/Alumnos/templates/base-2.html
<!DOCTYPE html>
<html lang="es">
<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="">
    <title>{{ title }}</title>

    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/087f668ea2.js" crossorigin="anonymous"></script>
    
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital@0;1&display=swap" rel="stylesheet">


    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    {% block head %}
    
    {% endblock %}

</head>
<body>
    <div class="contenedor">
        <div class="cabecera">
            
            {% include 'header.html' %}

        </div>    
        <div class="contenido">
        {% block content %}

        {% endblock %}
        </div> 
        <footer class="footer">
            {% include 'footer.html' %}
        </footer>
    </div>

{% block javascript %}


{% endblock %}

</body>


</html>

Apps/Alumnos/templates/base_login.html
<!DOCTYPE html>
<html lang="es">
<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/087f668ea2.js" crossorigin="anonymous"></script>
    
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital@0;1&display=swap" rel="stylesheet">


    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Datatables -->
    {% block head %}
    
    {% endblock %}

</head>
<body>
    <div class="container">
        {% block login %}

        {% endblock %}
    </div>

{% block javascript %}

{% endblock %}

</body>
</html>

Apps/Alumnos/templates/template_form.html
{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'lib/bootstrap-datepicker-1/css/bootstrap-datepicker3.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/bootstrap-datepicker-1/css/bootstrap-datepicker3.css' %}">

<script src="{% static 'lib/vendor/jquery/jquery.min.js' %}"></script>

<script src="{% static 'lib/bootstrap-datepicker-1/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'lib/bootstrap-datepicker-1/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'lib/bootstrap-datepicker-1/locales/bootstrap-datepicker.es.min.js' %}"></script>


{% endblock %}


{% block content %}

    
      <div class="card card-default">
        <div class="card-header">
          <h6 class="m-0 text-primary">{{ title }}</h6>
        </div>
        <!-- /.card-header -->
        <div class="card-body">

          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="col-sm-12">
                <!-- text input -->
                <div class="form-group">  
                 {{ form.as_p }}
                
                </div>
              </div>
            </div> 
            <button type="submit" class="btn btn-primary btn-sm btn-flat"><i class="fas fa-plus"></i> {{ submit }}</button>
            <a href="{{ cancel }}" class="btn btn-primary btn-sm btn-flat"><i class="fas fa-undo"></i> Volver</a>
          </form>

        </div>  
      </div>  
    

{% endblock %}



{% block javascript %}


<script>

$('#id_fecha').datepicker({
  format: 'dd-mm-yyyy',
  language: "es",
  keyboardNavigation: false,
  calendarWeeks: true,
  todayHighlight: true,
  toggleActive: true,
  autoclose: true
});

</script>

{% endblock %}